### ISSUE TITLE
No module named {pytest|'pebble'}

### ISSUE THREAD

**Issue by nickdesaulniers** [marxin/cvise#20]
Following up on https://github.com/marxin/cvise/issues/12. Today I pulled, and reran cmake, which failed.

```sh
$ cmake .. -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
...
  Pytest package not available: /usr/bin/python3.6: No module named pytest
  ModuleNotFoundError: No module named 'pebble'
```
but this worked with my previous checkout. In my shell history, I have:
```sh
$ pip3 install pebble pytest
```
so I thought I had these installed correctly? I tried wiping out my build dir and cmake cache files, but it made no difference.

Rerunning:
```sh
$ pip3 install pebble pytest
Requirement already satisfied: pebble in /usr/local/google/home/ndesaulniers/.local/lib/python3.7/site-packages (4.5.1)
Requirement already satisfied: pytest in /usr/local/google/home/ndesaulniers/.local/lib/python3.7/site-packages (5.4.1)
Requirement already satisfied: attrs>=17.4.0 in /usr/lib/python3/dist-packages (from pytest) (19.3.0)
Requirement already satisfied: pluggy<1.0,>=0.12 in /usr/local/google/home/ndesaulniers/.local/lib/python3.7/site-packages (from pytest) (0.13.1)
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from pytest) (19.1)
Requirement already satisfied: wcwidth in /usr/local/google/home/ndesaulniers/.local/lib/python3.7/site-packages (from pytest) (0.1.9)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /usr/local/google/home/ndesaulniers/.local/lib/python3.7/site-packages (from pytest) (1.6.0)
Requirement already satisfied: py>=1.5.0 in /usr/local/google/home/ndesaulniers/.local/lib/python3.7/site-packages (from pytest) (1.8.1)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/google/home/ndesaulniers/.local/lib/python3.7/site-packages (from pytest) (8.2.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/google/home/ndesaulniers/.local/lib/python3.7/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest) (3.1.0)
```
Those seem to mention python3.7, but the cmake failures for pytest mention python3.6. Is that related?

**Comment by marxin** [comment]
It's very likely related to 74492e90 where I started to use `${PYTHON_EXECUTABLE}`. It's documented here:
https://cmake.org/cmake/help/v3.0/module/FindPythonInterp.html

You will like need to set a `-DPYTHON_*` variable when running `cmake`, please take a look:
https://stackoverflow.com/questions/15291500/i-have-2-versions-of-python-installed-but-cmake-is-using-older-version-how-do
https://stackoverflow.com/questions/7660001/cmake-finds-wrong-python-libs

Or you can try using `virtualenv` which can fix it.

**Comment by nickdesaulniers** [comment]
Adding `-DPYTHON_EXECUTABLE=`which python3`` works, which expands to `-DPYTHON_EXECUTABLE=/usr/bin/python3`.

Though if I then run
`/android1/cvise/cvise.py --n 71 ./repro.sh compat3.i`
I then see #12 again, followed by a new crash:
```
...
ERROR Prereqs not found for pass ClexPass::define
ERROR Prereqs not found for pass ClangPass::rename-fun
ERROR Prereqs not found for pass ClangPass::rename-param
ERROR Prereqs not found for pass ClangPass::rename-var
ERROR Prereqs not found for pass ClangPass::rename-class
ERROR Prereqs not found for pass ClangPass::rename-cxx-method
ERROR Prereqs not found for pass ClangPass::combine-global-var
ERROR Prereqs not found for pass ClangPass::combine-local-var
ERROR Prereqs not found for pass ClangPass::simplify-struct-union-decl
ERROR Prereqs not found for pass ClangPass::move-global-var
ERROR Prereqs not found for pass ClangPass::unify-function-decl
ERROR Prereqs not found for pass ClexPass::rename-toks
ERROR Prereqs not found for pass ClexPass::delete-string
ERROR Prereqs not found for pass IndentPass::final
Traceback (most recent call last):
  File "/android1/cvise/cvise.py", line 227, in <module>
    reducer.reduce(pass_group, skip_initial=args.skip_initial_passes)
  File "/android1/cvise/cvise/cvise.py", line 112, in reduce
    self.test_manager.check_sanity()
  File "/android1/cvise/cvise/utils/testing.py", line 265, in check_sanity
    returncode = test_env.run_test()
  File "/android1/cvise/cvise/utils/testing.py", line 119, in run_test
    _, _, returncode = ProcessEventNotifier(self.pid_queue).run_process(cmd)
  File "/android1/cvise/cvise/passes/abstract.py", line 115, in run_process
    proc = subprocess.Popen(cmd, stdout=stdout, stderr=stderr, universal_newlines=True, encoding='utf8')
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/android0/kernel-all/repro.sh'
```

**Comment by marxin** [comment]
Ok, can you please attach the entire build log (including `cmake` run)? And what git revision do you build?
And I'm curious about content of `/android1/cvise/` folder and `/android1/cvise/cvise/`? Please cat `/android0/kernel-all/repro.sh` and can you run it independently?

**Comment by marxin** [comment]
@nickdesaulniers Have you came up to something please?

**Comment by nickdesaulniers** [comment]
> Please cat /android0/kernel-all/repro.sh

```sh
set -e
OUT=$(not clang -Wp,-MD,net/.compat.o.d  -nostdinc -isystem /android0/llvm-project/llvm/build/lib/clang/11.0.0/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -Qunused-arguments -Wall -Wundef -Werror=strict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -fno-PIE -Werror=implicit-function-declaration -Werror=implicit-int -Wno-format-security -std=gnu89 -no-integrated-as -Werror=unknown-warning-option -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -mno-80387 -mstack-alignment=8 -mtune=generic -mno-red-zone -mcmodel=kernel -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -DCONFIG_AS_ADX=1 -Wno-sign-compare -fno-asynchronous-unwind-tables -mretpoline-external-thunk -fno-delete-null-pointer-checks -Wno-frame-address -Wno-address-of-packed-member -O2 -Wframe-larger-than=2048 -fstack-protector-strong -Wno-format-invalid-specifier -Wno-gnu -Wno-tautological-compare -mno-global-merge -Wno-unused-const-variable -fomit-frame-pointer -Wdeclaration-after-statement -Wvla -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fno-stack-check -Werror=date-time -Werror=incompatible-pointer-types -fmacro-prefix-map=./= -fcf-protection=none -Wno-initializer-overrides -Wno-format -Wno-sign-compare -Wno-format-zero-length -Wno-pointer-to-enum-cast    -DKBUILD_MODFILE='"net/compat"' -DKBUILD_BASENAME='"compat"' -DKBUILD_MODNAME='"compat"' -c -o net/compat.o compat3.i 2>&1)

#echo $OUT | grep "'Live Variable Analysis' on function '@futex_lock_pi_atomic'" | grep "Can't find reaching def for virtreg" &>/dev/null
echo $OUT | grep "Running pass 'Greedy Register Allocator' on function '@compat_mc_setsockopt'" | grep '"Unexpected VNI"' &>/dev/null
```

> can you run it independently?

```sh
$ ./repro.sh 
$ echo $?
1
```
(fails locally, but that's because my current clang is setup to track a different bug, that shouldn't affect cvise though)

> And I'm curious about content of /android1/cvise/ folder 
```sh
$ ls
AUTHORS  build_and_test.sh  clex   cmake_config.h.in  COPYING  cvise.py  Docker      README.md
build    clang_delta        cmake  CMakeLists.txt     cvise    delta     INSTALL.md  TODO
```

> and /android1/cvise/cvise/?
```sh
$ ls cvise 
CMakeLists.txt  cvise.py  __init__.py  passes  pass_groups  __pycache__  tests  utils
```
> what git revision do you build?
```sh
$ it show -1 | head -n1
commit e8d954edf0ef6e0b7b4d7f90071c8f50d1bc2649
```
> can you please attach the entire build log (including cmake run)?
```sh
$ cmake .. -G Ninja -DCMAKE_C_COMPILER=/android1/android-master/prebuilts/clang/host/linux-x86/clang-r353983c/bin/clang -DCMAKE_CXX_COMPILER=/android1/android-master/prebuilts/clang/host/linux-x86/clang-r353983c/bin/clang++ -DPYTHON_EXECUTABLE=/usr/bin/python3

-- The C compiler identification is Clang 9.0.3
-- The CXX compiler identification is Clang 9.0.3
-- Check for working C compiler: /android1/android-master/prebuilts/clang/host/linux-x86/clang-r353983c/bin/clang
-- Check for working C compiler: /android1/android-master/prebuilts/clang/host/linux-x86/clang-r353983c/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /android1/android-master/prebuilts/clang/host/linux-x86/clang-r353983c/bin/clang++
-- Check for working CXX compiler: /android1/android-master/prebuilts/clang/host/linux-x86/clang-r353983c/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LLVM 11.0.0git
-- Using LLVMConfig.cmake in /android0/llvm-project/llvm/build/lib/cmake/llvm
-- Using ClangConfig.cmake in /android0/llvm-project/llvm/build/lib/cmake/clang
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.7.7", minimum required is "3.6") 
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG
-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG - Success
-- Using clang-format in /usr/bin/clang-format
-- Configuring done
-- Generating done
-- Build files have been written to: /android1/cvise/build
```
todo(nick): provide build log once my tree is resynced, currently dirty due to bisection I'm running.
todo(nick): pull master cvise and rebuild

**Comment by marxin** [comment]
Ok, so first observation is that you should run the `cvise.py` from build folder (and not source folder):

```shell
$ /android1/cvise/build/cvise.py ...
```

**Comment by marxin** [comment]
I was able to reproduce `OSError: [Errno 8] Exec format error:` and I hope it's fixed now.

**Comment by marxin** [comment]
@nickdesaulniers Have you managed to test `cvise` for some reduction?

**Comment by nickdesaulniers** [comment]
Sorry, no bugs just yet need reducing. (I don't even remember now which bug I was trying to use cvise anymore...too many bugs).  Been focused on enabling `-gz=zlib` and `-gdwarf-5` in the Linux kernel and `-fno-eliminate-unused-debug-types` in Clang.  Though we do have some some changes to our IR for `asm goto` waiting in the wings that cause aarch64 Linux kernels to fail to boot. I'll likely need cvise to produce a concise test case once I figure out what's going wrong there.

Sorry I wasn't more responsive verifying the fixes, but I promise I'll give cvise another shot soon, in place of creduce, and report back.  I appreciate your work on this!
