### ISSUE TITLE
cvise from git seems to miss an import: NameError: name 'subprocess' is not defined

### ISSUE THREAD

**Issue by trofi** [marxin/cvise#33]
Ran today's `cvise`: and observerd the crash:

```
$ cvise --remove-pass IfPass ./test_cvise.sh *.c
00:00:01 INFO ===< 834890 >===
00:00:01 INFO running 4 interestingness tests in parallel
00:00:01 INFO INITIAL PASSES
00:00:01 INFO ===< IncludesPass >===
00:00:16 INFO ===< UnIfDefPass >===
00:00:41 INFO ===< CommentsPass >===
00:00:45 INFO ===< LineMarkersPass >===
00:00:45 INFO ===< BlankPass >===
00:00:55 INFO (0.0%, 683496 bytes)
00:00:59 INFO ===< ClangBinarySearchPass::replace-function-def-with-decl >===
Traceback (most recent call last):
  File "/usr/share/cvise/passes/clangbinarysearch.py", line 51, in count_instances
    proc = subprocess.run(cmd, universal_newlines=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
NameError: name 'subprocess' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/cvise", line 265, in <module>
    reducer.reduce(pass_group, skip_initial=args.skip_initial_passes)
  File "/usr/share/cvise/cvise.py", line 122, in reduce
    self._run_additional_passes(pass_group["first"])
  File "/usr/share/cvise/cvise.py", line 145, in _run_additional_passes
    self.test_manager.run_pass(p)
  File "/usr/share/cvise/utils/testing.py", line 458, in run_pass
    self.state = self.current_pass.new(self.current_test_case)
  File "/usr/share/cvise/passes/clangbinarysearch.py", line 31, in new
    self.detect_best_standard(test_case)
  File "/usr/share/cvise/passes/clangbinarysearch.py", line 20, in detect_best_standard
    instances = self.count_instances(test_case)
  File "/usr/share/cvise/passes/clangbinarysearch.py", line 52, in count_instances
    except subprocess.SubprocessError:
NameError: name 'subprocess' is not defined
```

**Comment by trofi** [comment]
After adding `import subprocess` the failure looks like:

```
00:00:58 INFO ===< ClangBinarySearchPass::replace-function-def-with-decl >===
00:01:02 INFO using C++ standard: c++98 with 22 instances
Traceback (most recent call last):
  File "/usr/bin/cvise", line 265, in <module>
    reducer.reduce(pass_group, skip_initial=args.skip_initial_passes)
  File "/usr/share/cvise/cvise.py", line 122, in reduce
    self._run_additional_passes(pass_group["first"])
  File "/usr/share/cvise/cvise.py", line 145, in _run_additional_passes
    self.test_manager.run_pass(p)
  File "/usr/share/cvise/utils/testing.py", line 458, in run_pass
    self.state = self.current_pass.new(self.current_test_case)
  File "/usr/share/cvise/passes/clangbinarysearch.py", line 33, in new
    return BinaryState.create(self.count_instances(test_case))
NameError: name 'BinaryState' is not defined
```

**Comment by marxin** [comment]
Fixed now.
