### ISSUE TITLE
When are /tmp files cleared?

### ISSUE THREAD

**Issue by marehr** [marxin/cvise#62]
Hiho,

after running cvise for an extended time

```
> cvise --n 40 --skip-key-off --print-diff --timeout 120 --clang-delta-std=c++20 ./creduce_probe.sh ice.cpp

> cvise --version        
cvise 2.3.0 (38b42d9)
```

I got this error:

```
08:20:35 INFO (73.1%, 82693 bytes, 1644 lines)
Traceback (most recent call last):
  File "/usr/local/bin/cvise", line 286, in <module>
    reducer.reduce(pass_group, skip_initial=args.skip_initial_passes)
  File "/usr/local/share/cvise/cvise.py", line 146, in reduce
    self._run_main_passes(pass_group['main'])
  File "/usr/local/share/cvise/cvise.py", line 176, in _run_main_passes
    self.test_manager.run_pass(p)
  File "/usr/local/share/cvise/utils/testing.py", line 517, in run_pass
    success_env = self.run_parallel_tests()
  File "/usr/local/share/cvise/utils/testing.py", line 443, in run_parallel_tests
    test_env = TestEnvironment(self.state, order, self.test_script, folder,
  File "/usr/local/share/cvise/utils/testing.py", line 55, in __init__
    self.copy_files(test_case, additional_files)
  File "/usr/local/share/cvise/utils/testing.py", line 61, in copy_files
    shutil.copy(test_case, self.folder)
  File "/usr/lib/python3.9/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 275, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/usr/lib/python3.9/shutil.py", line 166, in _fastcopy_sendfile
    raise err from None
  File "/usr/lib/python3.9/shutil.py", line 152, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
OSError: [Errno 28] No space left on device: '/home/marehr/develope/seqan3-build/cvise/068-cvise-clang-14-gcclib-9-coordinate_matrix_simd_test/ice.cpp' -> '/tmp/cvise-zzbvxuwp/cvise-d4rw0cdm/ice.cpp'
```

my /tmp folder contains

```
> find /tmp -maxdepth 1 -type d -name "cvise-*" | wc -l
61
> du -hcs /tmp/cvise-*
492K	/tmp/cvise-0q4bn__9
0	/tmp/cvise-1axqrcpq
2.1M	/tmp/cvise-1nsmipmz
...
3.7M	/tmp/cvise-zzbvxuwp
99M	total

> find /tmp -maxdepth 1 -type f -name "ice-*" | wc -l
22278

> du -hcs /tmp/ice-*
1.9M	/tmp/ice-000530.cpp
8.0K	/tmp/ice-000530.sh
1.2M	/tmp/ice-000769.cpp
8.0K	/tmp/ice-000769.sh
...
8.0K	/tmp/ice-fffc10.sh
1.2M	/tmp/ice-fffd0e.cpp
8.0K	/tmp/ice-fffd0e.sh
1.2M	/tmp/ice-fffee2.cpp
8.0K	/tmp/ice-fffee2.sh
16G	total
```

I would expect that all those files will get regularly deleted during the reduction, as I didn't specify `--save-temps`.

**Comment by marxin** [comment]
Thank you for the report. I can confirm I used to have issues with temporary files, but that ought to be fixed.
Can you please share the content of `./creduce_probe.sh` file?

```
> find /tmp -maxdepth 1 -type d -name "cvise-*" | wc -l
61
```

This one is fishy, that should not happen. This one is weird:

```
1.9M	/tmp/ice-000530.cpp
8.0K	/tmp/ice-000530.sh
```

Because cvise operates only inside the created `/tmp/cvise-*` subfolders.

**Comment by marxin** [comment]
@marehr And you please test the pushed commit. It should help us investigating what leaves the `/tmp/cvise*` folders.

**Comment by marehr** [comment]
My `./creduce_probe.sh` files looks like this:

```bash
#!/bin/bash

set -o xtrace

SRC="ice.cpp"

CXX="DISTCC_HOSTS='localhost/6' DISTCC_SKIP_LOCAL_RETRY=1 /usr/bin/distcc /usr/local/bin/clang++-concepts" # bad compiler
CXX_FLAGS="-std=c++2a -pedantic -Wall -Wextra -pthread -fdiagnostics-color=always"
CXX_FLAGS="$CXX_FLAGS --gcc-toolchain=/opt/gcc/gcc-9/usr"
CXX_FLAGS="$CXX_FLAGS -I/usr/lib/clang/11.1.0/include"

# DISTCC_HOSTS='localhost/4'
CXX2="DISTCC_SKIP_LOCAL_RETRY=1 /usr/bin/distcc /group/ag_abi/software/bin/g++-11" # good compiler
CXX2_FLAGS="-std=c++2a -pedantic -Wall -Wextra -pthread -fdiagnostics-color=always"
INCLUDE_PATHS="-I/home/marehr/develope/seqan3/include/"
INCLUDE_PATHS="-I/home/marehr/develope/seqan3/test/unit/core/algorithm/ $INCLUDE_PATHS"
INCLUDE_PATHS="-I/home/marehr/develope/seqan3/test/unit/alignment/pairwise/ $INCLUDE_PATHS"
INCLUDE_PATHS="-I/home/marehr/develope/seqan3/test/include $INCLUDE_PATHS"
INCLUDE_PATHS="-I/home/marehr/develope/seqan3/submodules/cereal/include $INCLUDE_PATHS"
INCLUDE_PATHS="-I/home/marehr/develope/seqan3/submodules/range-v3/include $INCLUDE_PATHS"
INCLUDE_PATHS="-I/home/marehr/develope/seqan3/submodules/sdsl-lite/include $INCLUDE_PATHS"
INCLUDE_PATHS="-I/home/marehr/develope/seqan3-build/gcc-9-debug/vendor/googletest/googletest/include $INCLUDE_PATHS"

INCLUDE_PATHS="-I/home/marehr/develope/seqan3/test/unit/alignment/matrix/detail/ $INCLUDE_PATHS"

CMD="-I`pwd` $INCLUDE_PATHS $CXX_FLAGS -c $SRC"
CMD2="-I`pwd` $INCLUDE_PATHS $CXX2_FLAGS -c $SRC"

TIMEOUT_TIME=10s

timeout 100s bash -c "$CXX2 $CMD2" # >output 2>&1
if [ $? -ne 0 ]
then
    exit 1
fi

timeout 100s bash -c "$CXX $CMD " 2> output # this will return != 0 on seg fault
if [ $? -ne 0 ]
then
  cat output

  grep "PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script." output
  exit $? # segmentation faults are a success :)
else
  cat output
  exit 1 # no seg faults are no success :(
fi

```

I'm currently right within a reduction, I'll try out the patch once it is done.

Oh, I just noticed that the `ice-XXXXX.sh` files are artefacts generated by clang and not cvise

```
cat ice-89ad62.sh
# Crash reproducer for clang version 14.0.0 (git@github.com:llvm/llvm-project.git b31827f6641178905a866682c0d868b1ca436a5e)
# Driver args: "--driver-mode=g++" "-std=c++2a" "-Xclang" "-internal-isystem/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/include" "-Xclang" "-internal-isystem/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/include-fixed" "-I" "/tmp/cvise-akxcrblq/cvise-rshkjg94" "-I" "/home/marehr/develope/seqan3/test/unit/alignment/matrix/detail/" "-I" "/home/marehr/develope/seqan3-build/gcc-9-debug/vendor/googletest/googletest/include" "-I" "/home/marehr/develope/seqan3/submodules/sdsl-lite/include" "-I" "/home/marehr/develope/seqan3/submodules/range-v3/include" "-I" "/home/marehr/develope/seqan3/submodules/cereal/include" "-I" "/home/marehr/develope/seqan3/test/include" "-I" "/home/marehr/develope/seqan3/test/unit/alignment/pairwise/" "-I" "/home/marehr/develope/seqan3/test/unit/core/algorithm/" "-I" "/home/marehr/develope/seqan3/include/" "-std=c++2a" "-pedantic" "-Wall" "-Wextra" "-pthread" "-fdiagnostics-color=always" "--gcc-toolchain=/opt/gcc/gcc-9/usr" "-I" "/usr/lib/clang/11.1.0/include" "-c" "ice.cpp" "-o" "ice.o"
# Original command:  "/home/marehr/Packages/clang-concepts/pkg/bin/clang-13" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-emit-obj" "-mrelax-all" "--mrelax-relocations" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "ice.cpp" "-mrelocation-model" "static" "-mframe-pointer=all" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-munwind-tables" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-debugger-tuning=gdb" "-fcoverage-compilation-dir=/tmp/cvise-akxcrblq/cvise-rshkjg94" "-resource-dir" "/home/marehr/Packages/clang-concepts/pkg/lib/clang/14.0.0" "-I" "/tmp/cvise-akxcrblq/cvise-rshkjg94" "-I" "/home/marehr/develope/seqan3/test/unit/alignment/matrix/detail/" "-I" "/home/marehr/develope/seqan3-build/gcc-9-debug/vendor/googletest/googletest/include" "-I" "/home/marehr/develope/seqan3/submodules/sdsl-lite/include" "-I" "/home/marehr/develope/seqan3/submodules/range-v3/include" "-I" "/home/marehr/develope/seqan3/submodules/cereal/include" "-I" "/home/marehr/develope/seqan3/test/include" "-I" "/home/marehr/develope/seqan3/test/unit/alignment/pairwise/" "-I" "/home/marehr/develope/seqan3/test/unit/core/algorithm/" "-I" "/home/marehr/develope/seqan3/include/" "-I" "/usr/lib/clang/11.1.0/include" "-internal-isystem" "/opt/gcc/gcc-9/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0" "-internal-isystem" "/opt/gcc/gcc-9/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/x86_64-pc-linux-gnu" "-internal-isystem" "/opt/gcc/gcc-9/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/backward" "-internal-isystem" "/home/marehr/Packages/clang-concepts/pkg/lib/clang/14.0.0/include" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/opt/gcc/gcc-9/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/include" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-Wall" "-Wextra" "-pedantic" "-std=c++2a" "-fdeprecated-macro" "-fdebug-compilation-dir=/tmp/cvise-akxcrblq/cvise-rshkjg94" "-ferror-limit" "19" "-pthread" "-fgnuc-version=4.2.1" "-fno-implicit-modules" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-internal-isystem/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/include" "-internal-isystem/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/include-fixed" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-o" "ice.o" "-x" "c++" "ice.cpp"
 "/home/marehr/Packages/clang-concepts/pkg/bin/clang-13" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-emit-obj" "-mrelax-all" "--mrelax-relocations" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "ice.cpp" "-mrelocation-model" "static" "-mframe-pointer=all" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-munwind-tables" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-debugger-tuning=gdb" "-fcoverage-compilation-dir=/tmp/cvise-akxcrblq/cvise-rshkjg94" "-Wall" "-Wextra" "-pedantic" "-std=c++2a" "-fdeprecated-macro" "-fdebug-compilation-dir=/tmp/cvise-akxcrblq/cvise-rshkjg94" "-ferror-limit" "19" "-pthread" "-fgnuc-version=4.2.1" "-fno-implicit-modules" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-internal-isystem/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/include" "-internal-isystem/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/include-fixed" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-x" "c++" "ice-89ad62.cpp"
```

Ups, false alarm 🙈 

Sorry!

**Comment by marxin** [comment]
> Ups, false alarm 
> 
> Sorry!

That happens :)

**Comment by marehr** [comment]
Now I need to find out how to disable clang's auto-generated bug-reproducer files xD
