### ISSUE TITLE
Python crash in `process_done_futures` (AttributeError: 'NoneType' object has no attribute 'success')

### ISSUE THREAD

**Issue by andrewvaughanj** [marxin/cvise#9]
```
Traceback (most recent call last):
  File "/home/avj/cvise/build/cvise.py", line 229, in <module>
    reducer.reduce(pass_group, skip_initial=args.skip_initial_passes)
  File "/home/avj/cvise/build/cvise/cvise.py", line 124, in reduce
    self._run_additional_passes(pass_group["first"])
  File "/home/avj/cvise/build/cvise/cvise.py", line 151, in _run_additional_passes
    self.test_manager.run_pass(p)
  File "/home/avj/cvise/build/cvise/utils/testing.py", line 460, in run_pass
    success_env = self.run_parallel_tests()
  File "/home/avj/cvise/build/cvise/utils/testing.py", line 387, in run_parallel_tests
    quit_loop = self.process_done_futures()
  File "/home/avj/cvise/build/cvise/utils/testing.py", line 320, in process_done_futures
    if test_env.success:
AttributeError: 'NoneType' object has no attribute 'success'
```

**Comment by andrewvaughanj** [comment]
```
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/pebble/pool/process.py", line 178, in message_manager_loop
    pool_manager.process_next_message(SLEEP_UNIT)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/pebble/pool/process.py", line 210, in process_next_message
    message = self.worker_manager.receive(timeout)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/pebble/pool/process.py", line 342, in receive
    return self.pool_channel.recv()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/pebble/pool/channel.py", line 63, in recv
    return self.reader.recv()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/multiprocessing/connection.py", line 411, in _recv_bytes
    return self._recv(size)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
TypeError: an integer is required (got type NoneType)
```

**Comment by marxin** [comment]
The first should be fixed, the second issue is a known Pebble issue noxdafox/pebble#58.
